### ISSUE TITLE
Spiget Support

### ISSUE THREAD

**Issue by Cerexus** [JEFF-Media-GbR/Spigot-UpdateChecker#10]
Would be nice if you could add Spiget Support.

The Api from them is a bit faster, but returns Json format.

**Comment by mfnalex** [comment]
Nice idea, anyone's free to create a PR, I currently don't have time for this. I'll add it eventually when noone else does.

**Comment by Cerexus** [comment]
I wrote you on Discord, please read. Had some trouble... Maybe you have something to laugh too..

**Comment by mfnalex** [comment]
Added in 2.0.0 :)
