### ISSUE TITLE
Maven Repo is missing the newest Version

### ISSUE THREAD

**Issue by TrueMB** [JEFF-Media-GbR/Spigot-UpdateChecker#16]
I am trying to Update to the newest Version.
Version 2.1.1 yet doesn`t seem to be in the Repo.
https://hub.jeff-media.com/nexus/service/rest/repository/browse/jeff-media-public/de/jeff_media/SpigotUpdateChecker/

Thanks in Advance!

**Comment by mfnalex** [comment]
Hi, the group ID has changed to com.jeff_media :)

**Comment by mfnalex** [comment]
https://hub.jeff-media.com/nexus/#browse/browse:jeff-media-public:com%2Fjeff_media%2FSpigotUpdateChecker%2F2.1.1

**Comment by TrueMB** [comment]
Ahhh, thank you!
