### ISSUE TITLE
'Support' link placeholder

### ISSUE THREAD

**Issue by lokka30** [JEFF-Media-GbR/Spigot-UpdateChecker#18]
Hi @mfnalex, thanks for this awesome resource! I think I'll start using it soon.

One idea I could come up with to possibly improve this resource is to have a 'Support' link placeholder, like what Changelog, Donate and Download are. The Support link placeholder can just link users to a discord server or any other URL so that users can ask for help if they are confused with updating.

**Comment by mfnalex** [comment]
Good idea, I'm still busy updating all plugins to 1.18.2 right now, so feel free to create a PR :)
